declare var __DEV__: boolean
declare var __PROD__: boolean
declare var __VERSION__: string
declare namespace NodeJS {
    interface ProcessEnv {
        SHELL:string
        npm_command:string
        __ETC_PROFILE_DONE:string
        npm_config_userconfig:string
        COLORTERM:string
        __HM_SESS_VARS_SOURCED:string
        ANKI_WAYLAND:string
        HYPRLAND_CMD:string
        XDG_CONFIG_DIRS:string
        _JAVA_AWT_WM_NONEREPARENTING:string
        npm_config_cache:string
        _PYTHON_HOST_PLATFORM:string
        NIX_BUILD_CORES:string
        NIX_GCROOT:string
        TERM_PROGRAM_VERSION:string
        WLR_NO_HARDWARE_CURSORS:string
        configureFlags:string
        NVIM:string
        CLUTTER_BACKEND:string
        XDG_BACKEND:string
        mesonFlags:string
        PYTHONNOUSERSITE:string
        shell:string
        depsHostHost:string
        NODE:string
        PYTHONHASHSEED:string
        LC_ADDRESS:string
        LC_NAME:string
        XDG_DATA_HOME:string
        WARP_USE_SSH_WRAPPER:string
        STRINGS:string
        XDG_CONFIG_HOME:string
        depsTargetTarget:string
        XCURSOR_PATH:string
        stdenv:string
        COLOR:string
        LOCALE_ARCHIVE_2_27:string
        npm_config_local_prefix:string
        builder:string
        LIBVA_DRIVER_NAME:string
        NVIM_LOG_FILE:string
        LC_MONETARY:string
        NO_AT_BRIDGE:string
        shellHook:string
        XCURSOR_SIZE:string
        npm_config_globalconfig:string
        CONDA_CHANGEPS1:string
        EDITOR:string
        phases:string
        XDG_SEAT:string
        PWD:string
        XDG_VIDEOS_DIR:string
        NIX_PROFILES:string
        SOURCE_DATE_EPOCH:string
        LOGNAME:string
        XDG_SESSION_TYPE:string
        NIX_ENFORCE_NO_NATIVE:string
        CUPS_DATADIR:string
        NIX_PATH:string
        npm_config_init_module:string
        NIXPKGS_CONFIG:string
        CXX:string
        _:string
        TEMPDIR:string
        system:string
        XDG_PICTURES_DIR:string
        _PYTHON_SYSCONFIGDATA_NAME:string
        HOST_PATH:string
        TERMINAL:string
        QT_STYLE_OVERRIDE:string
        GTK2_RC_FILES:string
        IN_NIX_SHELL:string
        doInstallCheck:string
        HOME:string
        NIX_BINTOOLS:string
        XDG_PUBLICSHARE_DIR:string
        SSH_ASKPASS:string
        LC_PAPER:string
        LANG:string
        NIXOS_OZONE_WL:string
        ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE:string
        LS_COLORS:string
        _JAVA_AWT_WM_NONREPARENTING:string
        XDG_CURRENT_DESKTOP:string
        depsTargetTargetPropagated:string
        npm_package_version:string
        STARSHIP_SHELL:string
        VIMRUNTIME:string
        WAYLAND_DISPLAY:string
        cmakeFlags:string
        GIO_EXTRA_MODULES:string
        outputs:string
        WARP_HONOR_PS1:string
        XDG_DOWNLOAD_DIR:string
        NIX_STORE:string
        TMPDIR:string
        XDG_MUSIC_DIR:string
        WARP_COMBINED_PROMPT_COMMAND_GRID:string
        SSH_SOCKET_DIR:string
        LD:string
        XDG_TEMPLATES_DIR:string
        buildPhase:string
        INIT_CWD:string
        READELF:string
        GTK_A11Y:string
        STARSHIP_SESSION_KEY:string
        XDG_CACHE_HOME:string
        NIX_USER_PROFILE_DIR:string
        INFOPATH:string
        npm_lifecycle_script:string
        doCheck:string
        npm_config_npm_version:string
        GEM_HOME:string
        depsBuildBuild:string
        XDG_SESSION_CLASS:string
        XDG_DESKTOP_DIR:string
        PYTHONPATH:string
        TERM:string
        LC_IDENTIFICATION:string
        npm_package_name:string
        GTK_PATH:string
        FLAKE:string
        SIZE:string
        propagatedNativeBuildInputs:string
        npm_config_prefix:string
        LESSOPEN:string
        USER:string
        strictDeps:string
        SDL_VIDEODRIVER:string
        NVIM_SYSTEM_RPLUGIN_MANIFEST:string
        TZDIR:string
        AR:string
        AS:string
        HYPRLAND_INSTANCE_SIGNATURE:string
        TEMP:string
        NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu:string
        DISPLAY:string
        npm_lifecycle_event:string
        SHLVL:string
        MOZ_ENABLE_WAYLAND:string
        NIX_BUILD_TOP:string
        NM:string
        __HM_ZSH_SESS_VARS_SOURCED:string
        PAGER:string
        NIX_CFLAGS_COMPILE:string
        LC_TELEPHONE:string
        QTWEBKIT_PLUGIN_PATH:string
        patches:string
        LC_MEASUREMENT:string
        __NIXOS_SET_ENVIRONMENT_DONE:string
        XDG_VTNR:string
        buildInputs:string
        XDG_SESSION_ID:string
        preferLocalBuild:string
        LOCALE_ARCHIVE:string
        LESSKEYIN_SYSTEM:string
        npm_config_user_agent:string
        QML2_IMPORT_PATH:string
        TERMINFO_DIRS:string
        XDG_STATE_HOME:string
        npm_execpath:string
        LD_LIBRARY_PATH:string
        XDG_RUNTIME_DIR:string
        NODE_PATH:string
        depsBuildTarget:string
        OBJCOPY:string
        DETERMINISTIC_BUILD:string
        NIX_XDG_DESKTOP_PORTAL_DIR:string
        WARP_IS_LOCAL_SHELL_SESSION:string
        out:string
        LC_TIME:string
        npm_package_json:string
        XDG_DOCUMENTS_DIR:string
        LUA_CPATH:string
        STRIP:string
        XCURSOR_THEME:string
        XDG_DATA_DIRS:string
        GDK_BACKEND:string
        HUSHLOGIN:string
        LIBEXEC_PATH:string
        TMP:string
        OBJDUMP:string
        npm_config_noproxy:string
        PATH:string
        propagatedBuildInputs:string
        npm_config_node_gyp:string
        dontAddDisableDepTrack:string
        GTK_USE_PORTAL:string
        CC:string
        NIX_CC:string
        DBUS_SESSION_BUS_ADDRESS:string
        depsBuildTargetPropagated:string
        depsBuildBuildPropagated:string
        npm_config_global_prefix:string
        NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu:string
        QT_PLUGIN_PATH:string
        __NV_PRIME_RENDER_OFFLOAD:string
        LUA_PATH:string
        CONFIG_SHELL:string
        __structuredAttrs:string
        npm_node_execpath:string
        RANLIB:string
        NIX_HARDENING_ENABLE:string
        LC_NUMERIC:string
        OLDPWD:string
        NIX_LDFLAGS:string
        nativeBuildInputs:string
        name:string
        TERM_PROGRAM:string
        depsHostHostPropagated:string
    }
}
